project_id = "vzwnlgvggxfcbyamdarv"

[functions.tmb-test-connection]
verify_jwt = false

[functions.tmb-sync-products]
verify_jwt = false

[functions.password-reset]
verify_jwt = false

[functions.reset-password-confirm]
verify_jwt = false