// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzwnlgvggxfcbyamdarv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6d25sZ3ZnZ3hmY2J5YW1kYXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzc3OTAsImV4cCI6MjA2ODg1Mzc5MH0.Obg46XyXO0HGdacgpttOU_-4BAgg7UTRdd6gDLCiiXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});